version: '3.7'

services:
  web:
    image: php:8.0-apache
    container_name: moodle-web
    ports:
      - "8080:80"
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/www/moodledata
    depends_on:
      - db  
    environment:
      - MOODLE_DB_TYPE=mariadb
      - MOODLE_DB_HOST=db
      - MOODLE_DB_NAME=moodle
      - MOODLE_DB_USER=moodle
      - MOODLE_DB_PASSWORD=moodlepass
    working_dir: /var/www/html
    restart: unless-stopped
    command: >
      sh -c "docker-php-ext-install mysqli && apache2-foreground"

  db:
    image: mariadb:10.5
    container_name: moodle-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodlepass
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
