version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: moodle_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepass
    volumes:
      - mariadb_data:/var/lib/mysql

  moodle:
    image: moodle
    container_name: moodle_web
    restart: always
    ports:
      - "8080:80"
    environment:
      MOODLE_DATABASE: moodle
      MOODLE_USERNAME: moodleuser
      MOODLE_PASSWORD: moodlepass
      MOODLE_HOST: mariadb
    depends_on:
      - mariadb
    volumes:
      - moodle_data:/var/www/html
      - moodle_moodledata:/var/moodledata

volumes:
  mariadb_data:
  moodle_data:
  moodle_moodledata:
