version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - moodledata:/var/www/html/moodledata
    depends_on:
      - db

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: moodleroot
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodlepass
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  moodledata:
  dbdata:
